SELECT TOP (1000) [client_number]
      ,[first_name]
      ,[last_name]
      ,[email]
      ,[mobile_number]
      ,[date_of_birth]
      ,[gender]
      ,[province]
      ,[city]
      ,[signup_date]
      ,[event_type]
      ,[event_date]
      ,[account_number]
      ,[product_type]
      ,[account_status]
      ,[credit_limit]
      ,[loan_amount]
      ,[account_balance]
      ,[channel]
      ,[interaction_type]
      ,[resolved_flag]
      ,[transaction_type]
      ,[amount]
  FROM [stg_customer360].[dbo].[stg_customer360_raw]
